<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net9.0-windows10.0.19041.0;net11.0-windows10.0.19041.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ReactiveUI.Primitives" />
    <PackageReference Include="ReactiveUI.Primitives.Extensions" />
    <ProjectReference Include="..\TwinCATRx.SourceGenerators\TwinCATRx.SourceGenerators.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
    <ProjectReference Include="..\TwinCATRx\TwinCATRx.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="ReactiveUI.Primitives" />
    <Using Include="ReactiveUI.Primitives.Extensions" />
    <Using Include="ReactiveUI.Primitives.Signals" />
    <Using Include="ReactiveUI.Primitives.Signals.Signal" Alias="Observable" />
  </ItemGroup>

</Project>
