// Copyright (c) Chris Pulman. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CP.TwinCatRx.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public sealed class TwinCatReactiveStreamGenerator : IIncrementalGenerator
{
    private const string AttributeSource = """
// <auto-generated/>
#nullable enable
namespace CP.TwinCatRx;

[System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
internal sealed class TwinCatReactiveStreamAttribute : System.Attribute
{
    public TwinCatReactiveStreamAttribute(string variable, System.Type dataType)
    {
        Variable = variable;
        DataType = dataType;
    }

    public string Variable { get; }

    public System.Type DataType { get; }

    public string? Id { get; set; }

    public string? PropertyName { get; set; }

    public string? ObservableName { get; set; }
}
""";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx => ctx.AddSource("TwinCatReactiveStreamAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
                "CP.TwinCatRx.TwinCatReactiveStreamAttribute",
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) => GetStream(ctx))
            .Where(static stream => stream is not null);

        context.RegisterSourceOutput(candidates.Collect(), static (ctx, streams) => Execute(ctx, streams!));
    }

    private static StreamSpec? GetStream(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol classSymbol)
        {
            return null;
        }

        var specs = new List<ReactivePropertySpec>();
        foreach (var attribute in context.Attributes)
        {
            if (attribute.ConstructorArguments.Length != 2)
            {
                continue;
            }

            var variable = attribute.ConstructorArguments[0].Value as string;
            if (string.IsNullOrWhiteSpace(variable) || attribute.ConstructorArguments[1].Value is not INamedTypeSymbol dataType)
            {
                continue;
            }

            var propertyName = GetNamedString(attribute, "PropertyName") ?? SanitizeIdentifier(variable!);
            var observableName = GetNamedString(attribute, "ObservableName") ?? propertyName + "Observable";
            specs.Add(new ReactivePropertySpec(variable!, dataType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), GetNamedString(attribute, "Id"), propertyName, observableName));
        }

        return specs.Count == 0
            ? null
            : new StreamSpec(classSymbol.ContainingNamespace.IsGlobalNamespace ? null : classSymbol.ContainingNamespace.ToDisplayString(), classSymbol.Name, GetAccessibility(classSymbol), specs);
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<StreamSpec?> streams)
    {
        foreach (var group in streams.Where(static x => x is not null).GroupBy(static x => x!.Namespace + "." + x!.ClassName))
        {
            var spec = group.First()!;
            var properties = group.SelectMany(static x => x!.Properties).ToArray();
            context.AddSource($"{spec.ClassName}.TwinCatRx.g.cs", SourceText.From(Generate(spec, properties), Encoding.UTF8));
        }
    }

    private static string Generate(StreamSpec spec, IReadOnlyList<ReactivePropertySpec> properties)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>")
            .AppendLine("#nullable enable")
            .AppendLine("using System;")
            .AppendLine("using System.Reactive.Disposables;")
            .AppendLine("using System.Reactive.Linq;")
            .AppendLine("using System.Reactive.Subjects;")
            .AppendLine();

        if (spec.Namespace is not null)
        {
            sb.Append("namespace ").Append(spec.Namespace).AppendLine(";").AppendLine();
        }

        sb.Append(spec.Accessibility).Append(" partial class ").Append(spec.ClassName).AppendLine()
            .AppendLine("{");

        foreach (var property in properties)
        {
            sb.Append("    private readonly BehaviorSubject<").Append(property.TypeName).Append("?> _").Append(ToCamel(property.PropertyName)).Append("Subject = new(default);").AppendLine()
                .Append("    private ").Append(property.TypeName).Append("? _").Append(ToCamel(property.PropertyName)).AppendLine(";")
                .Append("    public ").Append(property.TypeName).Append("? ").Append(property.PropertyName).AppendLine()
                .AppendLine("    {")
                .Append("        get => _").Append(ToCamel(property.PropertyName)).AppendLine(";")
                .AppendLine("        private set")
                .AppendLine("        {")
                .Append("            _").Append(ToCamel(property.PropertyName)).AppendLine(" = value;")
                .Append("            _").Append(ToCamel(property.PropertyName)).AppendLine("Subject.OnNext(value);")
                .AppendLine("        }")
                .AppendLine("    }")
                .Append("    public IObservable<").Append(property.TypeName).Append("?> ").Append(property.ObservableName).Append(" => _").Append(ToCamel(property.PropertyName)).AppendLine("Subject.AsObservable();")
                .AppendLine();
        }

        sb.AppendLine("    public IDisposable BindTwinCatRx(CP.TwinCatRx.IRxTcAdsClient client)")
            .AppendLine("    {")
            .AppendLine("        if (client == null)")
            .AppendLine("        {")
            .AppendLine("            throw new ArgumentNullException(nameof(client));")
            .AppendLine("        }")
            .AppendLine()
            .AppendLine("        var subscriptions = new CompositeDisposable();");

        foreach (var property in properties)
        {
            sb.Append("        subscriptions.Add(CP.TwinCatRx.TwinCatRxExtensions.Observe<").Append(property.TypeName).Append(">(client, \"").Append(Escape(property.Variable)).Append('"');
            if (property.Id is not null)
            {
                sb.Append(", \"").Append(Escape(property.Id)).Append('"');
            }

            sb.Append(").Subscribe(value => ").Append(property.PropertyName).AppendLine(" = value));");
        }

        sb.AppendLine("        return subscriptions;")
            .AppendLine("    }")
            .AppendLine("}");

        return sb.ToString();
    }

    private static string? GetNamedString(AttributeData attribute, string name) =>
        attribute.NamedArguments.FirstOrDefault(x => x.Key == name).Value.Value as string;

    private static string GetAccessibility(INamedTypeSymbol symbol) =>
        symbol.DeclaredAccessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            _ => "internal",
        };

    private static string SanitizeIdentifier(string variable)
    {
        var text = new string(variable.Where(char.IsLetterOrDigit).ToArray());
        if (string.IsNullOrWhiteSpace(text))
        {
            return "Value";
        }

        return char.IsDigit(text[0]) ? "Value" + text : text;
    }

    private static string ToCamel(string value) => string.IsNullOrEmpty(value) ? "value" : char.ToLowerInvariant(value[0]) + value.Substring(1);

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private sealed class StreamSpec
    {
        public StreamSpec(string? ns, string className, string accessibility, IReadOnlyList<ReactivePropertySpec> properties)
        {
            Namespace = ns;
            ClassName = className;
            Accessibility = accessibility;
            Properties = properties;
        }

        public string? Namespace { get; }

        public string ClassName { get; }

        public string Accessibility { get; }

        public IReadOnlyList<ReactivePropertySpec> Properties { get; }
    }

    private sealed class ReactivePropertySpec
    {
        public ReactivePropertySpec(string variable, string typeName, string? id, string propertyName, string observableName)
        {
            Variable = variable;
            TypeName = typeName;
            Id = id;
            PropertyName = propertyName;
            ObservableName = observableName;
        }

        public string Variable { get; }

        public string TypeName { get; }

        public string? Id { get; }

        public string PropertyName { get; }

        public string ObservableName { get; }
    }
}
